MODEL_FEATURES = [
    "FIPS",
    "ZIP",
    "LON",
    "HEALTHCARE_EXPENSES",
    "HEALTHCARE_COVERAGE",
    "INCOME",
    "encounter_count",
    "encounter_type_count",
    "unique_encounter_count",
    "condition_count",
    "unique_condition_count",
    "medication_count",
    "unique_medication_count",
    "procedure_count",
    "unique_procedure_count",
    "careplan_count",
    "unique_careplan_count",
    "allergy_count",
    "device_count",
    "unique_device_count",
    "immunization_count",
    "unique_immunization_count",
    "claim_count",
    "unique_claim_diagnosis_count",
    "PREFIX_Mrs.",
    "PREFIX_Ms.",
    "PREFIX_Unknown",
    "SUFFIX_MD",
    "SUFFIX_PhD",
    "SUFFIX_Unknown",
    "MARITAL_M",
    "MARITAL_S",
    "MARITAL_Unknown",
    "MARITAL_W",
    "RACE_black",
    "RACE_hawaiian",
    "RACE_native",
    "RACE_other",
    "RACE_white",
    "ETHNICITY_nonhispanic",
    "GENDER_M",
    "COUNTY_Berkshire County",
    "COUNTY_Bristol County",
    "COUNTY_Dukes County",
    "COUNTY_Essex County",
    "COUNTY_Franklin County",
    "COUNTY_Hampden County",
    "COUNTY_Hampshire County",
    "COUNTY_Middlesex County",
    "COUNTY_Nantucket County",
    "COUNTY_Norfolk County",
    "COUNTY_Plymouth County",
    "COUNTY_Suffolk County",
    "COUNTY_Worcester County",
    "CITY_FREQUENCY",
    "age",
    "coverage_expense_ratio",
    "medication_per_encounter",
    "procedure_per_encounter",
    "condition_per_encounter",
    "claim_per_encounter",
]